name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1    
    - name: Build the Docker image
      run:  docker build . --file Dockerfile --tag krishnaprasadkv/sample-demo:v1      
    - name: login to the Docker hub
      run:  docker login --username "krishnaprasadkv" --password "KECT@qxty+k"    
    - name: push the Docker image
      run:  docker push krishnaprasadkv/sample-demo:v1
